---
pool:
  name: 'Azure pipelines'
  vmImage: ubuntu-latest

trigger:
  -main
steps:
- task: AzureCLI@2
  displayName: Azure CLI
  inputs:
    azureSubscription: <Azure_Resource_Manager_Service_Connection>
    scriptType: ps
    scriptLocation: inlineScript
    inlineScript: |
      az --version
      az account show