---
pool:
  name: 'azure-pipelines'
  vmImage: ubuntu-latest

trigger:
  - main

steps:
- task: Docker@2
  inputs:
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
    tags: '$(Build.BuildId)'
    addPipelineData: true 
    addBaseImageData: true


---
pool:
  name: 'azure-pipelines'
  vmImage: ubuntu-latest

trigger:
  - main

steps:
- script: 
  - docker compose -f local.yml build
  - docker compose -f local.yml run --rm django pytest
- displayName: running pytest

- script: 
  - docker compose -f local.yml run --rm django coverage run -m pytest
  - docker compose -f local.yml run --rm django coverage html
  - cd htmlcov
  - python -m http.server
- displayName: code converge


