---
pool: 'default'

trigger:
  - main

steps:
  - task: Maven@3
    inputs:
      mavenPOMFile: 'pom.xml' 
      goals: 'package'
      publishJUnitResults: true
      jdkVersionOption: '1.17'
      javaHomeOption: 'Path'
      jdkDirectory: /usr/lib/jvm/java-17-openjdk-amd64 
      mavenVersionOption: 'Path'
      mavenDirectory: /home/ubuntu/apache-maven-3.9.0
      
    