---
pool:
  name: 'azure-pipeline'
  vmImage: ubuntu-latest

trigger:
  - main

steps:
- task:  DotNetCoreCLI@2
  inputs:
    command: 'build' 
    publishWebProjects: true 
    publishTestResults: true
    projects: src/NopCommerce.sln


